python-path = /storage/packages/miniconda-24.9.2/envs/py310/bin/python

powerDraw:
	$(python-path) plotPowerDraw.py

power:
	$(python-path) plotPower.py

constructModel:
	$(python-path) constructModel.py